### ISSUE TITLE
Add sha256 or other checksum for the scripts

### ISSUE THREAD

**Issue by skelly37** [skelly37/nupac#41]
- [x] Research a cross-platform way to generate checksums
- [ ] Add `hash` metadata attribute with the checksums
- [ ] Check the sum validity when calling `generate-repo-cache.nu`, raise an error on mismatch
- [ ] Add to docs

**Comment by skelly37** [comment]
https://github.com/jonelo/jacksum/

**Comment by Yethal** [comment]
`open example.nu|hash sha256`

**Comment by skelly37** [comment]
> `open example.nu|hash sha256`

damn, didn’t know there was a built-in for it. even better
